
export default {
  ADD_WINDOW: 'ADD_WINDOW',
  UPDATE_WINDOW: 'UPDATE_WINDOW',
  REMOVE_WINDOW: 'REMOVE_WINDOW',

  ADD_MANIFEST: 'ADD_MANIFEST',
  UPDATE_MANIFEST: 'UPDATE_MANIFEST',
  REMOVE_MANIFEST: 'REMOVE_MANIFEST',

  ADD_COMPANION: 'ADD_COMPANION',
  UPDATE_COMPANION: 'UPDATE_COMPANION',
  REMOVE_COMPANION: 'REMOVE_COMPANION',
}
